#!/usr/bin/env python3
"""Write the AUR packages of a release: corvene-bin and corvene-full-bin.

    packaging/aur/stamp.py --version 0.2.0 --assets assets [--out target/aur]

Each package (`<out>/<name>/PKGBUILD` and its `.SRCINFO`) installs the
release's Linux .tar.gz (packaging/linux/package.sh: the `usr` tree of the
.deb) for x86_64, aarch64, i686 and armv7h (Arch Linux ARM's name for
armhf). An architecture whose archive is not in `--assets` is left out;
a package with none is not written. The sha256 sums are those of the files
in `--assets`, which must be the ones uploaded to the release.

Publishing: copy the two folders into clones of
ssh://aur@aur.archlinux.org/corvene-bin.git (and corvene-full-bin.git), then
commit and push. release.yml leaves them as the `aur` artifact.
"""

import argparse
import hashlib
from pathlib import Path

REPO = "https://github.com/wasi-master/corvene"
DESCRIPTION = "Native Git client that looks and works like GitHub Desktop"
# Arch's architecture names and the archives' (package.sh's ARCH)
ARCHITECTURES = [("x86_64", "x86_64"), ("aarch64", "aarch64"), ("i686", "i686"), ("armv7h", "armhf")]
DEPENDS = [
    "git",
    "glibc",
    "libxcb",
    "libxkbcommon",
    "libxkbcommon-x11",
    "fontconfig",
    "freetype2",
    "vulkan-icd-loader",
    "xdg-utils",
    "perl",
    "hicolor-icon-theme",
    "desktop-file-utils",
]
OPTDEPENDS = [
    "vulkan-driver: GPU rendering",
    "org.freedesktop.secrets: keep the account tokens (GNOME Keyring, KWallet, KeePassXC)",
    "hunspell-en_us: spell checking",
    "noto-fonts: the interface font",
]
PACKAGES = [
    # (name, archive prefix, conflicts)
    ("corvene-bin", "Corvene", ["corvene", "corvene-full-bin"]),
    ("corvene-full-bin", "Corvene-Full", ["corvene", "corvene-bin"]),
]


def sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as file:
        for block in iter(lambda: file.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def quoted(items):
    return " ".join(f"'{item}'" for item in items)


def write_package(out, name, prefix, conflicts, version, assets):
    archives = {}
    for arch, archive_arch in ARCHITECTURES:
        file = f"{prefix}-{version}-linux-{archive_arch}.tar.gz"
        if (assets / file).is_file():
            archives[arch] = (file, sha256(assets / file))
    if not archives:
        print(f"{name}: no Linux archive for {version} in {assets}; not written")
        return
    # pacman versions cannot hold "-"
    pkgver = version.replace("-", "_")
    url = f"{REPO}/releases/download/v{version}"
    description = DESCRIPTION + (" (every tree-sitter grammar built in)" if "full" in name else "")
    sources = "\n".join(
        f'source_{arch}=("{url}/{file}")\nsha256sums_{arch}=(\'{sum}\')' for arch, (file, sum) in archives.items()
    )
    pkgbuild = f"""# Maintainer: Wasi Master <corvene@wasimaster.com>
# Generated by packaging/aur/stamp.py in {REPO}; edit it there.
pkgname={name}
_version={version}
pkgver={pkgver}
pkgrel=1
pkgdesc="{description}"
arch=({quoted(archives)})
url="{REPO}"
license=('MIT')
depends=({quoted(DEPENDS)})
optdepends=({quoted(OPTDEPENDS)})
provides=('corvene')
conflicts=({quoted(conflicts)})
# a release build: already stripped, no debug info to split off
options=('!strip' '!debug')
{sources}

package() {{
  local arch="$CARCH"
  [[ "$arch" == armv7h ]] && arch=armhf
  cp -a "{prefix}-$_version-linux-$arch/usr" "$pkgdir/"
}}
"""
    srcinfo = [f"pkgbase = {name}", f"\tpkgdesc = {description}"]
    srcinfo += [f"\tpkgver = {pkgver}", "\tpkgrel = 1", f"\turl = {REPO}"]
    srcinfo += [f"\tarch = {arch}" for arch in archives]
    srcinfo += ["\tlicense = MIT"]
    srcinfo += [f"\tdepends = {d}" for d in DEPENDS]
    srcinfo += [f"\toptdepends = {d}" for d in OPTDEPENDS]
    srcinfo += ["\tprovides = corvene"]
    srcinfo += [f"\tconflicts = {c}" for c in conflicts]
    srcinfo += ["\toptions = !strip", "\toptions = !debug"]
    for arch, (file, sum) in archives.items():
        srcinfo += [f"\tsource_{arch} = {url}/{file}", f"\tsha256sums_{arch} = {sum}"]
    srcinfo += ["", f"pkgname = {name}", ""]
    folder = out / name
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "PKGBUILD").write_text(pkgbuild)
    (folder / ".SRCINFO").write_text("\n".join(srcinfo))
    print(f"{name}: {', '.join(archives)} → {folder}")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--version", required=True)
    parser.add_argument("--assets", required=True, type=Path, help="the folder with the release's .tar.gz files")
    parser.add_argument("--out", type=Path, default=Path("target/aur"))
    args = parser.parse_args()
    for name, prefix, conflicts in PACKAGES:
        write_package(args.out, name, prefix, conflicts, args.version, args.assets)


if __name__ == "__main__":
    main()
