//! The C table a built grammar library exports, laid out like
//! `corvene_grammars::Table` (ABI 1, `tools/ts-queries/build_unit.py`
//! writes the same for the packs). Only the name and the language
//! function are filled: the extension supplies queries and file
//! associations when the grammar is registered.

/// `table.c` for one grammar whose parser defines `symbol`.
pub fn table_c(name: &str, symbol: &str, version: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Corvene (corvene-extensions); the layout of corvene_grammars::Table (ABI 1).\n");
    out.push_str("#include <stddef.h>\n#include <stdint.h>\n");
    out.push_str(
        "typedef struct { const char *name; const void *(*language)(void); const char *highlights; \
         const char *injections; const char *locals; const char *extensions; const char *filenames; \
         const char *first_line; const char *aliases; const char *injects; } Grammar;\n",
    );
    out.push_str("typedef struct { uint32_t abi; const char *version; size_t len; const Grammar *grammars; } Table;\n");
    out.push_str(&format!("extern const void *{symbol}(void);\n"));
    out.push_str(&format!(
        "static const Grammar GRAMMARS[] = {{\n  {{\n    {},\n    (const void *(*)(void)){symbol},\n    \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\"\n  }}\n}};\n",
        c_string(name)
    ));
    out.push_str(&format!(
        "static const Table TABLE = {{1, {}, 1, GRAMMARS}};\n",
        c_string(version)
    ));
    out.push_str("#ifdef _WIN32\n__declspec(dllexport)\n#else\n__attribute__((visibility(\"default\")))\n#endif\n");
    out.push_str("const Table *corvene_grammars_v1(void) { return &TABLE; }\n");
    out
}

/// A C string literal (`?` escaped: `??=` is a trigraph in ISO C).
pub fn c_string(text: &str) -> String {
    let mut out = String::from("\"");
    for byte in text.bytes() {
        match byte {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            b'?' => out.push_str("\\?"),
            32..=126 => out.push(byte as char),
            _ => out.push_str(&format!("\\{byte:03o}")),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_names_the_symbol() {
        let c = table_c(
            "nix",
            "tree_sitter_nix",
            "nix-community-tree-sitter-nix@01234567",
        );
        assert!(c.contains("extern const void *tree_sitter_nix(void);"));
        assert!(c.contains("const Table *corvene_grammars_v1(void)"));
        assert!(c.contains("{1, \"nix-community-tree-sitter-nix@01234567\", 1, GRAMMARS}"));
        assert_eq!(c_string("a\"b\\c?d\né"), "\"a\\\"b\\\\c\\?d\\n\\303\\251\"");
    }
}
