#!/usr/bin/env python3
"""Octicons as Android vector drawables, for :core:design.

For each name in icons.txt: icons/<name>-16.svg and -24.svg from
@primer/octicons (MIT; a local `npm install @primer/octicons` in this
directory, else raw.githubusercontent.com/primer/octicons/main), written to
core/design/src/main/res/drawable/cvd_oct_<name>_{16,24}.xml with the path
data verbatim, plus Octicons.kt (one OcticonIcon per name). Fails on an SVG
with transforms or anything but <path> elements, so a drawable never quietly
differs from the original.

    python3 tools/octicons/gen.py
"""
import pathlib
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET

HERE = pathlib.Path(__file__).resolve().parent
ANDROID = HERE.parents[1]
RES = ANDROID / "core/design/src/main/res/drawable"
KOTLIN = ANDROID / "core/design/src/main/kotlin/com/wasimaster/corvene/design/Octicons.kt"
LOCAL = HERE / "node_modules/@primer/octicons/build/svg"
REMOTE = "https://raw.githubusercontent.com/primer/octicons/main/icons/{}.svg"
NS = "{http://www.w3.org/2000/svg}"


def svg(name):
    local = LOCAL / f"{name}.svg"
    if local.is_file():
        return local.read_text()
    with urllib.request.urlopen(REMOTE.format(name), timeout=30) as response:
        return response.read().decode()


def drawable(name, size):
    root = ET.fromstring(svg(f"{name}-{size}"))
    view = root.get("viewBox", f"0 0 {size} {size}").split()
    paths = []
    for element in root.iter():
        tag = element.tag.replace(NS, "")
        if tag in ("svg",):
            continue
        if tag != "path":
            sys.exit(f"{name}-{size}: unsupported <{tag}>")
        if element.get("transform"):
            sys.exit(f"{name}-{size}: path with a transform")
        rule = ' android:fillType="evenOdd"' if element.get("fill-rule") == "evenodd" else ""
        paths.append(f'    <path\n        android:fillColor="#FF000000"{rule}\n        android:pathData="{element.get("d")}" />')
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- Octicon {name}-{size} (@primer/octicons, MIT); generated by tools/octicons/gen.py -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size}dp"\n    android:height="{size}dp"\n'
        f'    android:viewportWidth="{view[2]}"\n    android:viewportHeight="{view[3]}">\n'
        + "\n".join(paths)
        + "\n</vector>\n"
    )


def camel(name):
    return "".join(part.capitalize() for part in re.split(r"[-_]", name))


def main():
    names = [line.strip() for line in (HERE / "icons.txt").read_text().splitlines() if line.strip() and not line.startswith("#")]
    RES.mkdir(parents=True, exist_ok=True)
    for old in RES.glob("cvd_oct_*.xml"):
        old.unlink()
    for name in names:
        for size in (16, 24):
            (RES / f"cvd_oct_{name.replace('-', '_')}_{size}.xml").write_text(drawable(name, size))
    def entry(n):
        d = n.replace('-', '_')
        line = f"    val {camel(n)} = OcticonIcon(\"{n}\", R.drawable.cvd_oct_{d}_16, R.drawable.cvd_oct_{d}_24)"
        if len(line) <= 140:
            return line
        # the house style's 140 columns: long names put the arguments on their own lines
        return f"    val {camel(n)} = OcticonIcon(\n        \"{n}\",\n        R.drawable.cvd_oct_{d}_16,\n        R.drawable.cvd_oct_{d}_24,\n    )"

    entries = "\n".join(entry(n) for n in names)
    KOTLIN.write_text(
        "// Generated by tools/octicons/gen.py from tools/octicons/icons.txt; do not edit.\n"
        "package com.wasimaster.corvene.design\n\n"
        "/** The Octicons the app ships (16 and 24 px each). */\n"
        "object Octicons {\n"
        f"{entries}\n"
        "}\n"
    )
    print(f"{len(names)} icons")


if __name__ == "__main__":
    main()
