#!/usr/bin/env bash
# Build the on-demand pack archives and their manifest.
#
#   packaging/packs.sh [out-dir]        # default: target/release-assets/packs
#   PACKS=tree-sitter-all packaging/packs.sh   # only some (space-separated)
#   PACK_OS=android PACKS="tree-sitter-all tree-sitter-rest" packaging/packs.sh
#                                       # the Android packs, from any host
#
# On Windows this runs in Git Bash, with Python as `python` (or PYTHON=<exe>)
# and LLVM's clang on the PATH.
#
# Produces in <out>:
# - tree-sitter-{all,rest}-<v>-<os>-<arch>.zip: corvene-grammars as ad-hoc
#   signed dylibs on macOS, shared objects on Linux (every grammar / the ones
#   (DLLs on Windows; in each case every grammar, or the ones
#   for languages GitHub Desktop does not highlight) plus the grammars' and
#   queries' licenses, one per architecture (the parse tables are ~170 MB per
#   architecture, so a universal file would double every download);
# - packs-manifest.json whose `url`s point at the `packs` GitHub release
#   (packaging/release.md): the archives and the manifest live there, not on
#   the app releases. Each entry carries the archive's sha256.
#
# Grammars without a committed parser.c are generated by tree-sitter CLI
# 0.27.0 (CORVENE_TREE_SITTER=<path>, or `tree-sitter` on PATH; node runs their
# grammar.js). On macOS the dylibs are built for every macOS Rust target
# installed (`rustup target add x86_64-apple-darwin` for Intel packs; a
# warning names the missing one); on Linux for the build machine's
# architecture (release.yml builds each natively).
set -euo pipefail

# C grammars compile for the oldest macOS Corvene supports (Info.plist
# LSMinimumSystemVersion; 11.0 on arm64), not for the build machine's
export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-10.15}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# corvene_grammars::PACK_VERSION (the `pack_version!` macro)
GRAMMARS_VERSION="$(grep -A3 'macro_rules! pack_version' "$ROOT/crates/corvene-grammars/src/lib.rs" | grep -m1 -oE '"[0-9][^"]*"' | tr -d '"')"
RELEASE_BASE="${RELEASE_BASE:-https://github.com/wasi-master/corvene/releases/download/packs}"
PACKS="${PACKS:-tree-sitter-all tree-sitter-rest}"
# --version: what release.yml compares with the `packs` release's manifest
if [[ "${1:-}" == --version ]]; then
  echo "$GRAMMARS_VERSION"
  exit 0
fi
OUT="${1:-$ROOT/target/release-assets/packs}"

mkdir -p "$OUT"
# absolute: the archives are written from inside the work directories
OUT="$(cd "$OUT" && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
ENTRIES="$WORK/entries.jsonl"
: > "$ENTRIES"

OS="$(uname -s)"
case "$OS" in
  MINGW* | MSYS* | CYGWIN*)
    WINDOWS=1
    # the tools read UTF-8 files and `cargo metadata`
    export PYTHONUTF8=1
    # python.org's installer has no `python3`; Git for Windows has no `zip`
    python3() { "${PYTHON:-python}" "$@"; }
    if ! command -v zip > /dev/null; then
      # the forms used below: zip -q [-r] -0|-9 <archive> <paths…>, adding
      # to an archive that exists
      zip() {
        python3 - "$@" << 'PY'
import os, sys, zipfile
flags = [a for a in sys.argv[1:] if a.startswith("-")]
archive, *paths = [a for a in sys.argv[1:] if not a.startswith("-")]
kind = zipfile.ZIP_STORED if "-0" in flags else zipfile.ZIP_DEFLATED
with zipfile.ZipFile(archive, "a", kind, compresslevel=None if "-0" in flags else 9) as out:
    for path in paths:
        if os.path.isdir(path):
            for folder, _, files in sorted(os.walk(path)):
                for name in sorted(files):
                    full = os.path.join(folder, name)
                    out.write(full, os.path.relpath(full).replace(os.sep, "/"))
        else:
            out.write(path, path.replace(os.sep, "/"))
PY
      }
    fi
    ;;
esac
if [[ "${PACK_OS:-}" == android ]]; then
  # PACK_OS=android cross-builds the grammar packs with the NDK's clang
  # (ANDROID_NDK_HOME) on any host, for both of Corvene's Android ABIs
  LIB_EXT=so
  NDK_BIN="$(dirname "$(find "${ANDROID_NDK_HOME:?PACK_OS=android needs ANDROID_NDK_HOME}/toolchains/llvm/prebuilt" -name llvm-nm | head -1)")"
  export CORVENE_CC="$NDK_BIN/clang" CORVENE_CXX="$NDK_BIN/clang++"
elif [[ "$OS" == Darwin ]]; then
  PACK_OS=macos LIB_EXT=dylib
elif [[ -n "${WINDOWS:-}" ]]; then
  PACK_OS=windows LIB_EXT=dll
else
  PACK_OS=linux LIB_EXT=so
fi

# name version kind zip [target]
add_entry() {
  local sha size
  sha="$(python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$4")"
  size="$(python3 -c 'import os,sys; print(os.path.getsize(sys.argv[1]))' "$4")"
  python3 - "$1" "$2" "$3" "$(basename "$4")" "$sha" "$size" "${5:-}" "$RELEASE_BASE" >> "$ENTRIES" <<'PY'
import json, sys
name, version, kind, file, sha, size, target, base = sys.argv[1:]
entry = {"name": name, "version": version, "min_app": "0.1.0", "url": f"{base}/{file}",
         "sha256": sha, "size": int(size), "kind": kind}
if target:
    entry["target"] = target
print(json.dumps(entry))
PY
  echo "built $4 ($size bytes, sha256 $sha)"
}

wants() { [[ " $PACKS " == *" $1 "* ]]; }

TARGETS=()
if [[ "$PACK_OS" == android ]]; then
  # API 26, the application's minimum
  TARGETS=(aarch64-linux-android26 armv7a-linux-androideabi26 x86_64-linux-android26 i686-linux-android26)
elif [[ "$PACK_OS" == macos ]]; then
  for t in aarch64-apple-darwin x86_64-apple-darwin; do
    if rustup target list --installed 2>/dev/null | grep -qx "$t"; then
      TARGETS+=("$t")
    else
      echo "warning: $t is not installed; no tree-sitter packs for it" >&2
    fi
  done
elif [[ "$PACK_OS" == windows ]]; then
  case "$(uname -m)" in
    x86_64) TARGETS=(x86_64-pc-windows-msvc) ;;
    aarch64 | arm64) TARGETS=(aarch64-pc-windows-msvc) ;;
    *) echo "warning: no tree-sitter packs for $(uname -m)" >&2 ;;
  esac
else
  case "$(uname -m)" in
    x86_64) TARGETS=(x86_64-unknown-linux-gnu) ;;
    aarch64 | arm64) TARGETS=(aarch64-unknown-linux-gnu) ;;
    *) echo "warning: no tree-sitter packs for $(uname -m)" >&2 ;;
  esac
fi

# Every grammar unit (a grammar package, or a grammar built from source) is
# its own small library (tools/ts-queries/build_unit.py: clang, a generated C
# table, no Rust std), gzipped: an installed pack unpacks and opens only the
# units a diff needs (corvene_highlight::treesitter::load_pack). UNITS=<names>
# limits the build (testing).
build_units() {
  local t="$1" arch="${1%%-*}" unit lib out
  out="$WORK/units-$arch"
  mkdir -p "$out"
  BUILT=()
  for unit in ${UNITS:-$(python3 "$ROOT/tools/ts-queries/gen.py" --units all | cut -d' ' -f1)}; do
    lib="$out/$unit.$LIB_EXT"
    if ! python3 "$ROOT/tools/ts-queries/build_unit.py" "$unit" "$lib" --target "$t" 2>"$WORK/build-$unit.log"; then
      echo "warning: the $unit grammar did not build for $arch; left out:" >&2
      tail -3 "$WORK/build-$unit.log" >&2
      continue
    fi
    if [[ "$PACK_OS" == macos ]]; then
      # arm64 code must carry a signature; the linker's is kept, re-sign to be sure
      codesign --force --sign - --timestamp=none "$lib" 2>/dev/null
      nm -gU "$lib" | grep -q '_corvene_grammars_v1$' || { echo "$lib does not export corvene_grammars_v1" >&2; exit 1; }
    elif [[ "$PACK_OS" == windows ]]; then
      llvm-readobj --coff-exports "$lib" | grep -q 'Name: corvene_grammars_v1$' || { echo "$lib does not export corvene_grammars_v1" >&2; exit 1; }
    else
      "${NDK_BIN:+$NDK_BIN/llvm-}nm" -D --defined-only "$lib" | grep -q ' corvene_grammars_v1$' || { echo "$lib does not export corvene_grammars_v1" >&2; exit 1; }
    fi
    gzip -9 -n -c "$lib" > "$lib.gz"
    rm "$lib"
    BUILT+=("$unit")
  done
}

# variant (all | rest), arch
grammar_pack() {
  local variant="$1" arch="$2" dir zip unit
  dir="$WORK/tree-sitter-$variant-$arch"
  mkdir -p "$dir/grammars"
  for unit in $(python3 "$ROOT/tools/ts-queries/gen.py" --units "$variant" | cut -d' ' -f1); do
    [[ -f "$WORK/units-$arch/$unit.$LIB_EXT.gz" ]] && cp "$WORK/units-$arch/$unit.$LIB_EXT.gz" "$dir/grammars/"
  done
  python3 "$ROOT/tools/ts-queries/gen.py" --ext "$LIB_EXT" --index "$variant" "${BUILT[@]}" > "$dir/index.json"
  cp "$ROOT/crates/corvene-grammars/THIRD_PARTY.md" "$dir/THIRD_PARTY.md"
  zip="$OUT/tree-sitter-$variant-$GRAMMARS_VERSION-$PACK_OS-$arch.zip"
  rm -f "$zip"
  # the units are gzipped already: store them
  (cd "$dir" && zip -q -r -0 "$zip" grammars && zip -q -9 "$zip" index.json THIRD_PARTY.md)
  add_entry "tree-sitter-$variant" "$GRAMMARS_VERSION" "tree-sitter-$variant" "$zip" "$PACK_OS-$arch"
}

if wants tree-sitter-all || wants tree-sitter-rest; then
  python3 "$ROOT/tools/ts-queries/fetch.py" >/dev/null
  for t in "${TARGETS[@]}"; do
    echo "building the tree-sitter grammar units for ${t%%-*}…"
    build_units "$t"
    wants tree-sitter-all && grammar_pack all "${t%%-*}"
    wants tree-sitter-rest && grammar_pack rest "${t%%-*}"
  done
fi

python3 - "$ENTRIES" > "$OUT/packs-manifest.json" <<'PY'
import json, sys
packs = [json.loads(line) for line in open(sys.argv[1]) if line.strip()]
print(json.dumps({"schema": 1, "packs": packs}, indent=2))
PY
echo "manifest: $OUT/packs-manifest.json"
